package be.msdc.hypco.internal.ui.theme

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF254DE4)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFDDE1FF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001257)
internal val md_theme_light_secondary = Color(0xFF005EB4)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFFD5E3FF)
internal val md_theme_light_onSecondaryContainer = Color(0xFF001B3C)
internal val md_theme_light_tertiary = Color(0xFF006496)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFCCE5FF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF001E31)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFFEFBFF)
internal val md_theme_light_onBackground = Color(0xFF1B1B1F)
internal val md_theme_light_surface = Color(0xFFFEFBFF)
internal val md_theme_light_onSurface = Color(0xFF1B1B1F)
internal val md_theme_light_surfaceVariant = Color(0xFFE3E1EC)
internal val md_theme_light_onSurfaceVariant = Color(0xFF45464F)
internal val md_theme_light_outline = Color(0xFF767680)
internal val md_theme_light_inverseOnSurface = Color(0xFFF3F0F4)
internal val md_theme_light_inverseSurface = Color(0xFF303034)
internal val md_theme_light_inversePrimary = Color(0xFFB9C3FF)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF254DE4)
internal val md_theme_light_surfaceTintColor = Color(0xFF254DE4)

internal val md_theme_dark_primary = Color(0xFFB9C3FF)
internal val md_theme_dark_onPrimary = Color(0xFF00228A)
internal val md_theme_dark_primaryContainer = Color(0xFF0033C1)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFDDE1FF)
internal val md_theme_dark_secondary = Color(0xFFA8C8FF)
internal val md_theme_dark_onSecondary = Color(0xFF003061)
internal val md_theme_dark_secondaryContainer = Color(0xFF004689)
internal val md_theme_dark_onSecondaryContainer = Color(0xFFD5E3FF)
internal val md_theme_dark_tertiary = Color(0xFF90CDFF)
internal val md_theme_dark_onTertiary = Color(0xFF003350)
internal val md_theme_dark_tertiaryContainer = Color(0xFF004B72)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFCCE5FF)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF1B1B1F)
internal val md_theme_dark_onBackground = Color(0xFFE4E1E6)
internal val md_theme_dark_surface = Color(0xFF1B1B1F)
internal val md_theme_dark_onSurface = Color(0xFFE4E1E6)
internal val md_theme_dark_surfaceVariant = Color(0xFF45464F)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC6C5D0)
internal val md_theme_dark_outline = Color(0xFF90909A)
internal val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
internal val md_theme_dark_inverseSurface = Color(0xFFE4E1E6)
internal val md_theme_dark_inversePrimary = Color(0xFF254DE4)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFFB9C3FF)
internal val md_theme_dark_surfaceTintColor = Color(0xFFB9C3FF)

internal val seed = Color(0xFF234BE2)